</br>
<h2 id ="OOB">Read Data from TinyEHR</h2>
</br>

#### Install TinyEHR

In [1]:
!pip install -q tinyehr

#### Import Packages

In [2]:
import tinyehr
import sqlite3 as sql3
import pandas as pd

#### Build a Local SQLite Database of TinyEHR (MIMIC Format)

In [3]:
db_path_mimic = tinyehr.build_sqlite(format='tinyehr_mimic_format', output='C:\\tinyehr\\tinyehr_mimic_format.db')

  [1/33] admissions... 275 rows
  [2/33] caregiver... 15,468 rows
  [3/33] chartevents... 668,862 rows
  [4/33] d_hcpcs... 89,200 rows
  [5/33] d_icd_diagnoses... 109,775 rows
  [6/33] d_icd_procedures... 85,257 rows
  [7/33] d_items... 4,014 rows
  [8/33] d_labitems... 1,622 rows
  [9/33] date_offsets... 100 rows
  [10/33] datetimeevents... 15,280 rows
  [11/33] diagnoses_icd... 4,506 rows
  [12/33] drgcodes... 454 rows
  [13/33] emar... 35,835 rows
  [14/33] emar_detail... 72,018 rows
  [15/33] hcpcsevents... 61 rows
  [16/33] icustays... 140 rows
  [17/33] ingredientevents... 25,728 rows
  [18/33] inputevents... 20,404 rows
  [19/33] labevents... 107,727 rows
  [20/33] microbiologyevents... 2,899 rows
  [21/33] noteevents... 4,580 rows
  [22/33] omr... 2,964 rows
  [23/33] outputevents... 9,362 rows
  [24/33] patients... 100 rows
  [25/33] pharmacy... 15,306 rows
  [26/33] poe... 45,154 rows
  [27/33] poe_detail... 3,795 rows
  [28/33] prescriptions... 18,087 rows
  [29/33] procedureevents... 1,468 rows
  [30/33] procedures_icd... 722 rows
  [31/33] provider... 40,508 rows
  [32/33] services... 319 rows
  [33/33] transfers... 1,190 rows

SQLite database: C:\tinyehr\tinyehr_mimic_format.db

#### Connect to the Database

In [4]:
conn_mimic = sql3.connect(db_path_mimic)
conn_mimic.execute('select * from admissions limit 1').fetchall()

[(10004235,
  24181354,
  '2014-02-24 14:38:00',
  '2014-03-04 14:02:00',
  None,
  'URGENT',
  'P03YMR',
  'TRANSFER FROM HOSPITAL',
  'SKILLED NURSING FACILITY',
  'Medicaid',
  'ENGLISH',
  'SINGLE',
  'BLACK/CAPE VERDEAN',
  '2014-02-24 12:15:00',
  '2014-02-24 17:07:00',
  0)]

#### Load Data in as Pandas DataFrames

In [5]:
query = 'select * from patients;'
patients = pd.read_sql(query, conn_mimic)
patients.head()

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10014729,F,21,2013,2011 - 2013,None
1,10003400,F,72,2011,2011 - 2013,2014-09-02 00:00:00
2,10002428,F,80,2011,2011 - 2013,None
3,10032725,F,38,2013,2011 - 2013,2013-03-30 00:00:00
4,10027445,F,48,2012,2011 - 2013,2016-02-09 00:00:00

In [6]:
# Some common parameters
# coerce_float: Attempt to force numbers into floats
# parse_dates: List of columns to parse as dates
# chunksize: Number of rows to include in each chunk

patients_generator = pd.read_sql(query, 
                          conn_mimic,
                          coerce_float=True,
                          parse_dates=['dod'],
                          chunksize=5)
for id, patient in enumerate(patients_generator):
    if id < 5:
        print(f'patient id: {id}'.format(id))
        display(patient)

patient id: 0

   subject_id gender  anchor_age  anchor_year anchor_year_group        dod
0    10014729      F          21         2013       2011 - 2013        NaT
1    10003400      F          72         2011       2011 - 2013 2014-09-02
2    10002428      F          80         2011       2011 - 2013        NaT
3    10032725      F          38         2013       2011 - 2013 2013-03-30
4    10027445      F          48         2012       2011 - 2013 2016-02-09

patient id: 1

   subject_id gender  anchor_age  anchor_year anchor_year_group        dod
0    10037928      F          78         2011       2011 - 2013        NaT
1    10001725      F          46         2011       2011 - 2013        NaT
2    10040025      F          64         2011       2011 - 2013 2016-02-07
3    10008454      F          26         2013       2011 - 2013        NaT
4    10020640      F          91         2011       2011 - 2013 2012-02-04

patient id: 2

   subject_id gender  anchor_age  anchor_year anchor_year_group dod
0    10014078      F          60         2013       2011 - 2013 NaT
1    10007795      F          53         2013       2011 - 2013 NaT
2    10001217      F          55         2013       2011 - 2013 NaT
3    10019172      F          63         2011       2011 - 2013 NaT
4    10039831      F          57         2013       2011 - 2013 NaT

patient id: 3

   subject_id gender  anchor_age  anchor_year anchor_year_group        dod
0    10007928      F          59         2012       2011 - 2013        NaT
1    10019003      F          65         2011       2011 - 2013 2018-12-03
2    10002930      F          48         2011       2011 - 2013 2019-12-24
3    10010471      F          89         2014       2014 - 2016 2014-12-07
4    10027602      F          71         2014       2014 - 2016        NaT

patient id: 4

   subject_id gender  anchor_age  anchor_year anchor_year_group        dod
0    10031757      F          67         2014       2014 - 2016 2014-10-31
1    10016742      F          58         2016       2014 - 2016        NaT
2    10039997      F          67         2016       2014 - 2016        NaT
3    10012853      F          91         2014       2014 - 2016        NaT
4    10000032      F          52         2016       2014 - 2016 2016-09-09